CREATE DATABASE PRESUPUESTOS
USE PRESUPUESTOS
CREATE TABLE USUARIOS(ID INT IDENTITY(1,1) NOT NULL, NOMBRE1 VARCHAR(50) NOT NULL,
NOMBRE2 VARCHAR(50) NULL, APELLIDO1 VARCHAR(50) NOT NULL, APELLIDO2 VARCHAR(50) NOT NULL, MAIL VARCHAR(50) NOT NULL,
PASS_WORD VARCHAR(50) NOT NULL, USERNAME VARCHAR(50) NOT NULL, ACTIVO INT NOT NULL, PRIMARY KEY(USERNAME))

USE PRESUPUESTOS
CREATE TABLE INDEXPRESUPUESTOS(ID INT NOT NULL IDENTITY(1,1), ID_PRESUPUESTO VARCHAR(30) NOT NULL, 
CREADO_EN DATE NOT NULL, PROYECTO VARCHAR(100) NOT NULL, VERSION INT NOT NULL, ACTIVO INT NOT NULL, PRIMARY
KEY(ID_PRESUPUESTO))

ALTER TABLE INDEXPRESUPUESTOS
ADD CONSTRAINT PK_INDEXPRESUPUESTOS_ID_PRESUPUESTO PRIMARY KEY CLUSTERED(ID_PRESUPUESTO)

CREATE TABLE INGRESOS(ID INT NOT NULL IDENTITY(1,1), ID_PRESUPUESTO VARCHAR(30) NOT NULL, 
CONCEPTO VARCHAR(100) NOT NULL, MES VARCHAR(20) NOT NULL, TOTAL FLOAT NOT NULL, FOREIGN KEY(ID_PRESUPUESTO)
REFERENCES INDEXPRESUPUESTOS(ID_PRESUPUESTO))


CREATE TABLE COSTOSDIRECTOS(ID INT NOT NULL IDENTITY(1,1), ID_PRESUPUESTO VARCHAR(30) NOT NULL, 
CONCEPTO VARCHAR(100) NOT NULL, MES VARCHAR(20) NOT NULL, TOTAL FLOAT NOT NULL, FOREIGN KEY(ID_PRESUPUESTO)
REFERENCES INDEXPRESUPUESTOS(ID_PRESUPUESTO))

CREATE TABLE GASTOSADMINISTRATIVOS(ID INT NOT NULL IDENTITY(1,1), ID_PRESUPUESTO VARCHAR(30) NOT NULL, 
CONCEPTO VARCHAR(100) NOT NULL, MES VARCHAR(20) NOT NULL, TOTAL FLOAT NOT NULL, FOREIGN KEY(ID_PRESUPUESTO)
REFERENCES INDEXPRESUPUESTOS(ID_PRESUPUESTO))


CREATE TABLE RECURSOS(ID INT NOT NULL IDENTITY(1,1), ID_PRESUPUESTO VARCHAR(30) NOT NULL, 
CONCEPTO VARCHAR(100) NOT NULL, MES VARCHAR(20) NOT NULL, PORCENTAJE FLOAT NOT NULL,COSTO FLOAT NOT NULL, FOREIGN KEY(ID_PRESUPUESTO)
REFERENCES INDEXPRESUPUESTOS(ID_PRESUPUESTO))